name: Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL5LIB: c:\cx\lib\perl5
  PERL_LOCAL_LIB_ROOT: c:/cx
  PERL_MB_OPT: --install_base C:/cx
  PERL_MM_OPT: INSTALL_BASE=C:/cx
  ALIEN_BUILD_PRELOAD: Fetch::Cache
  #AUTOMATED_TESTING: 1

jobs:
  build-share:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
      - name: perl -V
        run: |
          echo $env:PATH
          perl -V
        
      - name: Prepare for CPAN cache
        run: |
          perl -V > perlversion.txt
          echo '20220330' >> perlversion.txt
          dir perlversion.txt

      - name: Cache CPAN modules
        uses: actions/cache@v1
        with:
          path: c:\cx
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Prepare for Alien cache
        run: |
          perl -V > aliencache.txt
          echo 'aliens 20220330' >> aliencache.txt
          dir aliencache.txt

      - name: Cache Alien downloads
        uses: actions/cache@v1
        with:
          path: C:\Users\runneradmin\.alienbuild
          key: ${{ runner.os }}-build-${{ hashFiles('aliencache.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('aliencache.txt') }}

      - name: Install dependencies 1
        run: |
          cpanm --notest --installdeps .
  
      - name: Install dependencies Alien::MSYS
        run: |
          cpanm --notest Alien::MSYS

      - name: Build system
        run: |
          perl Makefile.PL
          cpanm --installdeps .
          gmake
          gmake test

